name: update-wa-version

on:
  workflow_dispatch:

jobs:
  update-wa-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Setup GIT
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Setup Node
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 16.x

      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"

      - name: Setup npm cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm ci || npm install

      - name: Last release of wa-version
        id: wa_version
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: wppconnect-team
          repo: wa-version
          excludes: prerelease, draft

      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: "wppconnect-team/wa-version"
          ref: ${{ steps.wa_version.outputs.release }}
          path: "packages/wa-version"

      - name: Install Dependencies of wa-version
        run: (cd packages/wa-version && (npm ci || npm install))

      - name: Build Page
        run: npm run build

      - uses: EndBug/add-and-commit@v8
        with:
          message: "chore: Update API of wa-version"
          committer_name: GitHub Actions
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
